In [1]:
data_prod = catalog.load("raw_prod")

                    INFO     Loading data from raw_prod (ParquetDataset)...                     ]8;id=332023;file:///home/rosana/.conda/envs/PD_env_1/lib/python3.11/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=608062;file:///home/rosana/.conda/envs/PD_env_1/lib/python3.11/site-packages/kedro/io/data_catalog.py#401\401]8;;\

In [2]:
data_prod

action_type combined_shot_type  game_event_id   game_id      lat  loc_x  \
10      Jump Shot          Jump Shot            309  20000012  33.8063    -94   
17      Jump Shot          Jump Shot            138  20000019  33.8183   -117   
27      Jump Shot          Jump Shot            369  20000019  33.8583   -183   
39      Jump Shot          Jump Shot            202  20000047  33.7723    -27   
54      Jump Shot          Jump Shot             60  20000049  33.7973   -141   
...           ...                ...            ...       ...      ...    ...   
30675   Jump Shot          Jump Shot             84  49900088  33.8283   -134   
30681   Jump Shot          Jump Shot            218  49900088  33.7833    -18   
30685   Jump Shot          Jump Shot            249  49900088  33.7943     81   
30689   Jump Shot          Jump Shot            326  49900088  33.3653    -12   
30695   Jump Shot          Jump Shot            448  49900088  33.7773     31   

       loc_y       lon  minutes_remaining  period  ...       shot_type  \
10       238 -118.3638                  1       3  ...  3PT Field Goal   
17       226 -118.3868                  8       2  ...  3PT Field Goal   
27       186 -118.4528                  0       3  ...  3PT Field Goal   
39       272 -118.2968                  0       2  ...  3PT Field Goal   
54       247 -118.4108                  4       1  ...  3PT Field Goal   
...      ...       ...                ...     ...  ...             ...   
30675    216 -118.4038                  2       1  ...  3PT Field Goal   
30681    261 -118.2878                  0       2  ...  3PT Field Goal   
30685    250 -118.1888                  7       3  ...  3PT Field Goal   
30689    679 -118.2818                  0       3  ...  3PT Field Goal   
30695    267 -118.2388                  2       4  ...  3PT Field Goal   

             shot_zone_area    shot_zone_basic  shot_zone_range     team_id  \
10     Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
17     Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
27     Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
39                Center(C)  Above the Break 3          24+ ft.  1610612747   
54     Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
...                     ...                ...              ...         ...   
30675  Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
30681             Center(C)  Above the Break 3          24+ ft.  1610612747   
30685             Center(C)  Above the Break 3          24+ ft.  1610612747   
30689        Back Court(BC)          Backcourt  Back Court Shot  1610612747   
30695             Center(C)  Above the Break 3          24+ ft.  1610612747   

                team_name   game_date      matchup opponent  shot_id  
10     Los Angeles Lakers  2000-10-31    LAL @ POR      POR       11  
17     Los Angeles Lakers  2000-11-01  LAL vs. UTA      UTA       18  
27     Los Angeles Lakers  2000-11-01  LAL vs. UTA      UTA       28  
39     Los Angeles Lakers  2000-11-04    LAL @ VAN      VAN       40  
54     Los Angeles Lakers  2000-11-05  LAL vs. LAC      LAC       55  
...                   ...         ...          ...      ...      ...  
30675  Los Angeles Lakers  2000-06-19  LAL vs. IND      IND    30676  
30681  Los Angeles Lakers  2000-06-19  LAL vs. IND      IND    30682  
30685  Los Angeles Lakers  2000-06-19  LAL vs. IND      IND    30686  
30689  Los Angeles Lakers  2000-06-19  LAL vs. IND      IND    30690  
30695  Los Angeles Lakers  2000-06-19  LAL vs. IND      IND    30696  

[6426 rows x 25 columns]

In [3]:
data_prod

action_type combined_shot_type  game_event_id   game_id      lat  loc_x  \
10      Jump Shot          Jump Shot            309  20000012  33.8063    -94   
17      Jump Shot          Jump Shot            138  20000019  33.8183   -117   
27      Jump Shot          Jump Shot            369  20000019  33.8583   -183   
39      Jump Shot          Jump Shot            202  20000047  33.7723    -27   
54      Jump Shot          Jump Shot             60  20000049  33.7973   -141   
...           ...                ...            ...       ...      ...    ...   
30675   Jump Shot          Jump Shot             84  49900088  33.8283   -134   
30681   Jump Shot          Jump Shot            218  49900088  33.7833    -18   
30685   Jump Shot          Jump Shot            249  49900088  33.7943     81   
30689   Jump Shot          Jump Shot            326  49900088  33.3653    -12   
30695   Jump Shot          Jump Shot            448  49900088  33.7773     31   

       loc_y       lon  minutes_remaining  period  ...       shot_type  \
10       238 -118.3638                  1       3  ...  3PT Field Goal   
17       226 -118.3868                  8       2  ...  3PT Field Goal   
27       186 -118.4528                  0       3  ...  3PT Field Goal   
39       272 -118.2968                  0       2  ...  3PT Field Goal   
54       247 -118.4108                  4       1  ...  3PT Field Goal   
...      ...       ...                ...     ...  ...             ...   
30675    216 -118.4038                  2       1  ...  3PT Field Goal   
30681    261 -118.2878                  0       2  ...  3PT Field Goal   
30685    250 -118.1888                  7       3  ...  3PT Field Goal   
30689    679 -118.2818                  0       3  ...  3PT Field Goal   
30695    267 -118.2388                  2       4  ...  3PT Field Goal   

             shot_zone_area    shot_zone_basic  shot_zone_range     team_id  \
10     Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
17     Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
27     Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
39                Center(C)  Above the Break 3          24+ ft.  1610612747   
54     Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
...                     ...                ...              ...         ...   
30675  Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
30681             Center(C)  Above the Break 3          24+ ft.  1610612747   
30685             Center(C)  Above the Break 3          24+ ft.  1610612747   
30689        Back Court(BC)          Backcourt  Back Court Shot  1610612747   
30695             Center(C)  Above the Break 3          24+ ft.  1610612747   

                team_name   game_date      matchup opponent  shot_id  
10     Los Angeles Lakers  2000-10-31    LAL @ POR      POR       11  
17     Los Angeles Lakers  2000-11-01  LAL vs. UTA      UTA       18  
27     Los Angeles Lakers  2000-11-01  LAL vs. UTA      UTA       28  
39     Los Angeles Lakers  2000-11-04    LAL @ VAN      VAN       40  
54     Los Angeles Lakers  2000-11-05  LAL vs. LAC      LAC       55  
...                   ...         ...          ...      ...      ...  
30675  Los Angeles Lakers  2000-06-19  LAL vs. IND      IND    30676  
30681  Los Angeles Lakers  2000-06-19  LAL vs. IND      IND    30682  
30685  Los Angeles Lakers  2000-06-19  LAL vs. IND      IND    30686  
30689  Los Angeles Lakers  2000-06-19  LAL vs. IND      IND    30690  
30695  Los Angeles Lakers  2000-06-19  LAL vs. IND      IND    30696  

[6426 rows x 25 columns]

In [4]:
rows = data_prod.head(10).drop(columns=['shot_made_flag'])
rows

action_type combined_shot_type  game_event_id   game_id      lat  loc_x  \
10   Jump Shot          Jump Shot            309  20000012  33.8063    -94   
17   Jump Shot          Jump Shot            138  20000019  33.8183   -117   
27   Jump Shot          Jump Shot            369  20000019  33.8583   -183   
39   Jump Shot          Jump Shot            202  20000047  33.7723    -27   
54   Jump Shot          Jump Shot             60  20000049  33.7973   -141   
55   Jump Shot          Jump Shot             80  20000049  33.8503   -155   
56   Jump Shot          Jump Shot            105  20000049  33.8163      1   
59   Jump Shot          Jump Shot            199  20000049  33.8033    146   
67   Jump Shot          Jump Shot             28  20000058  33.9873    231   
71   Jump Shot          Jump Shot             73  20000058  33.7873      7   

    loc_y       lon  minutes_remaining  period  ...       shot_type  \
10    238 -118.3638                  1       3  ...  3PT Field Goal   
17    226 -118.3868                  8       2  ...  3PT Field Goal   
27    186 -118.4528                  0       3  ...  3PT Field Goal   
39    272 -118.2968                  0       2  ...  3PT Field Goal   
54    247 -118.4108                  4       1  ...  3PT Field Goal   
55    194 -118.4248                  2       1  ...  3PT Field Goal   
56    228 -118.2688                 11       2  ...  3PT Field Goal   
59    241 -118.1238                  3       2  ...  3PT Field Goal   
67     57 -118.0388                  8       1  ...  3PT Field Goal   
71    257 -118.2628                  3       1  ...  3PT Field Goal   

           shot_zone_area    shot_zone_basic  shot_zone_range     team_id  \
10   Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
17   Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
27   Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
39              Center(C)  Above the Break 3          24+ ft.  1610612747   
54   Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
55   Left Side Center(LC)  Above the Break 3          24+ ft.  1610612747   
56              Center(C)          Mid-Range        16-24 ft.  1610612747   
59  Right Side Center(RC)  Above the Break 3          24+ ft.  1610612747   
67          Right Side(R)     Right Corner 3          24+ ft.  1610612747   
71              Center(C)  Above the Break 3          24+ ft.  1610612747   

             team_name   game_date      matchup  opponent shot_id  
10  Los Angeles Lakers  2000-10-31    LAL @ POR       POR      11  
17  Los Angeles Lakers  2000-11-01  LAL vs. UTA       UTA      18  
27  Los Angeles Lakers  2000-11-01  LAL vs. UTA       UTA      28  
39  Los Angeles Lakers  2000-11-04    LAL @ VAN       VAN      40  
54  Los Angeles Lakers  2000-11-05  LAL vs. LAC       LAC      55  
55  Los Angeles Lakers  2000-11-05  LAL vs. LAC       LAC      56  
56  Los Angeles Lakers  2000-11-05  LAL vs. LAC       LAC      57  
59  Los Angeles Lakers  2000-11-05  LAL vs. LAC       LAC      60  
67  Los Angeles Lakers  2000-11-07    LAL @ HOU       HOU      68  
71  Los Angeles Lakers  2000-11-07    LAL @ HOU       HOU      72  

[10 rows x 24 columns]

In [5]:
data_prod['playoffs'].value_counts()


playoffs
0    5544
1     882
Name: count, dtype: int64

In [6]:
data_prod['shot_type'].value_counts()


shot_type
3PT Field Goal    6426
Name: count, dtype: int64

In [7]:
data_prod.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6426 entries, 10 to 30695
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   action_type         6426 non-null   object 
 1   combined_shot_type  6426 non-null   object 
 2   game_event_id       6426 non-null   int64  
 3   game_id             6426 non-null   int64  
 4   lat                 6426 non-null   float64
 5   loc_x               6426 non-null   int64  
 6   loc_y               6426 non-null   int64  
 7   lon                 6426 non-null   float64
 8   minutes_remaining   6426 non-null   int64  
 9   period              6426 non-null   int64  
 10  playoffs            6426 non-null   int64  
 11  season              6426 non-null   object 
 12  seconds_remaining   6426 non-null   int64  
 13  shot_distance       6426 non-null   int64  
 14  shot_made_flag      5412 non-null   float64
 15  shot_type           6426 non-null   object 
 16  shot_zone

In [36]:
data_processed_x = (data_prod[['lat', 'lon','minutes_remaining','period','playoffs','shot_distance']]
        .assign(playoffs = lambda x: x['playoffs'].astype(bool))
       )   
data_processed_x['lat_quadra'] = data_processed_x['lat'] - 34.0443
data_processed_x['lon_quadra'] = data_processed_x['lon'] + 118.2698
data_processed_x = data_processed_x.drop(columns=["lat", "lon"])

data_processed_x

minutes_remaining  period  playoffs  shot_distance  lat_quadra  \
10                     1       3     False             25      -0.238   
17                     8       2     False             25      -0.226   
27                     0       3     False             26      -0.186   
39                     0       2     False             27      -0.272   
54                     4       1     False             28      -0.247   
...                  ...     ...       ...            ...         ...   
30675                  2       1      True             25      -0.216   
30681                  0       2      True             26      -0.261   
30685                  7       3      True             26      -0.250   
30689                  0       3      True             67      -0.679   
30695                  2       4      True             26      -0.267   

       lon_quadra  
10         -0.094  
17         -0.117  
27         -0.183  
39         -0.027  
54         -0.141  
...           ...  
30675      -0.134  
30681      -0.018  
30685       0.081  
30689      -0.012  
30695       0.031  

[6426 rows x 6 columns]

In [45]:
import pickle


with open("../data/06_models/RL_model.pkl", "rb") as file:
    rl_model = pickle.load(file)

# Check the loaded model
print(rl_model)

LogisticRegression(C=8.235, class_weight='balanced', max_iter=1000,
                   random_state=3128)


In [46]:
import pickle


with open("../data/06_models/DT_model.pkl", "rb") as file:
    dt_model = pickle.load(file)

# Check the loaded model
print(dt_model)

DecisionTreeClassifier(random_state=3128)


In [52]:
rl_prod_predictions = rl_model.predict(data_processed_x)
print(dt_prod_predictions) 

rl_prod_probabilities = rl_model.predict_proba(data_processed_x)[:, 1]
print(dt_prod_probabilities)  

[0. 0. 0. ... 0. 0. 0.]
[0.36602181 0.36920003 0.33090937 ... 0.3497439  0.10289385 0.34563519]


In [53]:
dt_prod_predictions = dt_model.predict(data_processed_x)
print(dt_prod_predictions) 

dt_prod_probabilities = dt_model.predict_proba(data_processed_x)[:, 1]
print(dt_prod_probabilities)  

[0. 1. 1. ... 1. 1. 0.]
[0. 1. 1. ... 1. 1. 0.]


In [ ]:
import requests
import pandas as pd
import numpy as np

# Carregamos os dados de produção
data_prod_ok = data_prod.replace([np.inf, -np.inf], 1e10).fillna(0)

# Limitamos a 10 registros para teste
sample_data = data_prod_ok

# Formato esperado pelo MLflow 2.0+
payload = {
    "dataframe_split": {
        "columns": sample_data.columns.tolist(),
        "data": sample_data.values.tolist()
    }
}

# Enviamos a requisição
resp = requests.post(
    'http://127.0.0.1:5002/invocations',
    json=payload,
    headers={"Content-Type": "application/json"}
)

print(f"Status code: {resp.status_code}")
if resp.status_code == 200:
    print(f"Resposta: {resp.json()}")
else:
    print(f"Erro: {resp.text}")

data_prod

In [ ]:
# Verificar as colunas do DataFrame
print("Colunas no DataFrame:", data_prod.columns.tolist())

# Verificar se todas as colunas necessárias estão presentes
colunas_necessarias = ['lat', 'lon', 'minutes_remaining', 'period', 'playoffs', 'shot_distance']
colunas_faltando = [col for col in colunas_necessarias if col not in data_prod.columns]
if colunas_faltando:
    print(f"Atenção: as seguintes colunas estão faltando: {colunas_faltando}")
else:
    print("Todas as colunas necessárias estão presentes")

In [ ]:
import pickle


with open("../data/06_models/best_model.pkl", "rb") as file:
    model = pickle.load(file)

# Check the loaded model
print(model)

In [ ]:

data_dev = catalog.load("raw_dev")

data_dev_filtered = (data_dev[['lat', 'lon','minutes_remaining','period','playoffs','shot_distance']]
        # .assign(playoffs = lambda x: x['playoffs'].astype(bool))
        )        
if "playoffs" in data_dev_filtered.columns:
    data_dev_filtered["playoffs"] = data_dev_filtered["playoffs"].astype(bool)
        
if {"lat", "lon"}.issubset(data_dev_filtered.columns):
    data_dev_filtered["lat_quadra"] = data_dev_filtered["lat"] - 34.0443
    data_dev_filtered["lon_quadra"] = data_dev_filtered["lon"] + 118.2698
    data_dev_filtered = data_dev_filtered.drop(columns=["lat", "lon"])
        
print(data_dev_filtered)


data_prod_filtered = (data_prod[['lat', 'lon','minutes_remaining','period','playoffs','shot_distance']]
        # .assign(playoffs = lambda x: x['playoffs'].astype(bool))
        )        
if "playoffs" in data_prod_filtered.columns:
    data_prod_filtered["playoffs"] = data_prod_filtered["playoffs"].astype(bool)
        
if {"lat", "lon"}.issubset(data_prod_filtered.columns):
    data_prod_filtered["lat_quadra"] = data_prod_filtered["lat"] - 34.0443
    data_prod_filtered["lon_quadra"] = data_prod_filtered["lon"] + 118.2698
    data_prod_filtered = data_prod_filtered.drop(columns=["lat", "lon"])
        
print(data_prod_filtered)
print('shot_distance_dev')
print(data_dev_filtered['shot_distance'].value_counts())
print('shot_distance_prod')
print(data_prod_filtered['shot_distance'].value_counts())

In [ ]:
import matplotlib.pyplot as plt

# Supondo que 'data_dev_filtered' seja um DataFrame do Pandas
plt.hist(data_dev_filtered['shot_distance'], bins=30, edgecolor='black')

plt.xlabel('Distância do Shot - DEV')
plt.ylabel('Frequência')
plt.title('Histograma de Distância do Shot - DEV')

plt.show()

In [ ]:
import matplotlib.pyplot as plt

# Supondo que 'data_dev_filtered' seja um DataFrame do Pandas
plt.hist(data_prod_filtered['shot_distance'], bins=30, edgecolor='black')

plt.xlabel('Distância do Shot - PROD')
plt.ylabel('Frequência')
plt.title('Histograma de Distância do Shot - PROD')

plt.show()

In [ ]:
import numpy as np

prediction_dev = model.predict(data_dev_filtered)
prediction_prod = model.predict(data_prod_filtered)

print(prediction_dev[0:30])
print(prediction_prod[0:30])

In [ ]:
data_dev['shot_type'].value_counts()

In [ ]:
data_prod['shot_type'].value_counts()